# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1d081890ce5a9e1b22856b5575d82935a2aa73a08aca0b0ef7341b01d817e73b3360cf715f58d74822c5c53214846ad8796efd466234eaea736839ef3c3260a

test:
  secret_key_base: 0b14c4cc860714fea4530f7babd2ad8b48f35447c535479b68a163bdb186c2239576b3dab65f5f9ecea7a80cc9e37469954f0b8df183578267cbdc376aeadfba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
